networks:
  postgres_normal_mi-red-postgres:
    external: true

services:
  biotik-back:
    build:
      context: ./biotik-back
    container_name: biotik-back
    env_file:
      - .env  # Cargar variables desde el archivo .env en la ruta base
    environment:
      - BACK_PORT=${BACK_PORT}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5035:5000"
    networks:
      - postgres_normal_mi-red-postgres
    restart: ${RESTART_POLICY}

  biotik-web:
    env_file:
      - .env  # Cargar variables desde el archivo .env en la ruta base
    environment:
      - VITE_API_URL=${VITE_API_URL}
    build:
      context: ./biotik-web
      args:
        VITE_API_URL: ${VITE_API_URL}  # Pasa la variable al Dockerfile
    container_name: biotik-web
    ports:
      - "3035:3000"
    networks:
      - postgres_normal_mi-red-postgres
    depends_on:
      - biotik-back
    restart: ${RESTART_POLICY}

