version: '3.9'

networks:
  mi-red-biotik:

services:
  postgres-biotik:
    image: postgres:15.4-bullseye
    container_name: postgres-biotik
    env_file:
      - .env  # Cargar variables desde el archivo .env en la ruta base
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./pg_backup:/pg_backup
    ports:
      - "5435:5432"
    networks:
      - mi-red-biotik

  biotik-back:
    build:
      context: ./biotik-back
    container_name: biotik-back
    env_file:
      - .env  # Cargar variables desde el archivo .env en la ruta base
    environment:
      - BACK_PORT=${BACK_PORT}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5035:5000"
    networks:
      - mi-red-biotik
    depends_on:
      - postgres-biotik


  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin-biotik
    env_file:
      - .env  # Cargar variables desde el archivo .env en la ruta base
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_ADDRESS=${PGADMIN_LISTEN_ADDRESS}
      - PGADMIN_SERVER_MODE=${PGADMIN_SERVER_MODE}
    ports:
      - "8035:80"
    networks:
      - mi-red-biotik
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

  biotik-web:
    build:
      context: ./biotik-web
    container_name: biotik-web
    ports:
      - "3035:3000"
    networks:
      - mi-red-biotik
    depends_on:
      - biotik-back

